FROM nginx:latest
LABEL maintainer="Sezgin CEYLAN @dukakbey" 
ENV user="sezgin"
ARG color
RUN apt-get update && apt-get install -y curl htop wget
WORKDIR /TEMP
ADD https://wordpress.org/latest.tar.gz .
WORKDIR  /usr/share/nginx/html
COPY html/${color} .
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost || exit 1
#CMD [ "./script.sh" ]